VS Code: Upgrade `@types/vscode` and `engine` to `v1.100.0` (#1646)
This pull request updates the VS Code version (`engine.vscode`) to be
`v1.100.0` or newer. This version was released on [May 8,
2025](https://code.visualstudio.com/updates/v1_100).

Additionally, this fixes the issue that lets the VS Code extension from
being published in CI, since the versions mismatched:

```
cd javascript/packages/vscode && npx @vscode/vsce publish --no-dependencies

Error: @types/vscode ^1.115.0 greater than engines.vscode ^1.43.0. Either upgrade engines.vscode or use an older @types/vscode version
Error: Process completed with exit code 1.
```