Add sig/manifest.yaml to declare stdlib dependencies
`sig/herb/token_list.rbs` declares a class inheriting from
`SimpleDelegator`, which comes from the `delegate` standard library.
Since `delegate` is a default gem, it does not appear in the gemspec,
and `rbs collection install` cannot resolve it on the consumer side.

With Steep 2.0, this previously-silent issue surfaces as a hard error:

    Type checking failed due to error in library RBS file
    Cannot find type `SimpleDelegator`
    (.../herb-0.10.1/sig/herb/token_list.rbs:4:2)
    Diagnostic ID: Ruby::LibraryRBSError

Declare the implicit standard library dependencies in
`sig/manifest.yaml` so downstream users get correct type resolution.

Refs: https://github.com/ruby/rbs/blob/master/docs/gem.md